title:              Hengjia Zhang
tagline:            at the University of Michigan
description:        CSE Graduate Student at Umich
url:                http://hengjia.github.io

author:
  name:             Hengjia Zhang
  url:              https://github.com/hengjia
  email:            hengjia@umich.edu

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
